create user PRIME_NUMBERS IDENTIFIED by primeNumberUser;

grant all PRIVILEGES to PRIME_NUMBERS;

CREATE TABLE PRIME_NUMBERS 
(
  NUMBERS NUMBER NOT NULL 
, CONSTRAINT PRIME_NUMBERS_PK PRIMARY KEY 
  (
    NUMBERS 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PRIME_NUMBERS_PK ON PRIME_NUMBERS (NUMBERS ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
