
  CREATE TABLE "PINCODEADMINUSER"."PROPERTY" 
   (	"PROPERTY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"AD_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ADDRESS_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRICE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STREET_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FLOOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DOOR_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ELEVATOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ADDRESS_SIZE" NUMBER(*,0) NOT NULL ENABLE, 
	"ROOM_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BALCONY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AIR_CONDITIONER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"GARDEN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PANEL_PROGRAM" NUMBER(*,0) NOT NULL ENABLE, 
	"HEIGHT" FLOAT(126) NOT NULL ENABLE, 
	"PROPERTY_CONDITION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
	"COUNT_NUMBER" NUMBER(*,0), 
	 CONSTRAINT "PROPERTY_ID_PK" PRIMARY KEY ("PROPERTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "PINCODEADMINUSER"."USER_DATA" ("USER_ID") ENABLE, 
	 CONSTRAINT "CLIENT_FK" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "PINCODEADMINUSER"."CLIENT" ("CLIENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."PROPERTY_ID" IS 'Ingatlan egyedi azonosító';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."CLIENT_ID" IS 'Ügyfél azonosító';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."USER_ID" IS 'Felhasználó azonosító';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."AD_TYPE" IS 'Hirdetés típusa';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."ADDRESS_TYPE" IS 'Cím típusa (Lakás, ház, telek, stb)';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."PRICE" IS 'Ár';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."CITY" IS 'Város';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."DISTRICT" IS 'Kerület';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."STREET" IS 'Utca neve';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."STREET_NUMBER" IS 'Házszám';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."FLOOR" IS 'Emeletszám';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."DOOR_NUMBER" IS 'Ajtószám';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."ELEVATOR" IS 'Lift';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."STATUS" IS 'Ingatlan státusza';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."ADDRESS_SIZE" IS 'Ingatlan mérete';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."ROOM_NUMBER" IS 'Szobák száma';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."BALCONY" IS 'Erkélyes';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."AIR_CONDITIONER" IS 'Légkondícionáló';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."GARDEN" IS 'Kertkapcsolat';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."PANEL_PROGRAM" IS 'Az ingatlan részt vett-e panel programban?';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."HEIGHT" IS 'Ingatlan magassága';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."PROPERTY_CONDITION" IS 'Ingatlan állapota (Új építés, felújított, felújítandó, stb)';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."DESCRIPTION" IS 'Ingatlan leírás';
   COMMENT ON COLUMN "PINCODEADMINUSER"."PROPERTY"."COUNT_NUMBER" IS 'Nézettség';
