-- Törli a szekvenciális sorszám növelést
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE PROPERTY_SEQ;
DROP SEQUENCE CLIENT_SEQ;

-- Rögzíti a szekvenciális sorszám növelést
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PROPERTY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 1;

--ADATTÁBLÁK TARTALMÁNAK TÖRLÉSE! MINDENT TÖRÖL!

-- TÖRLI A PROPERTY TÁBLA USER IDEGEN KULCS KAPCSOLATÁT
ALTER TABLE PROPERTY DROP CONSTRAINT USER_FK;
-- TÖRLI A PROPERTY TÁBLA CLIENT IDEGEN KULCS KAPCSOLATÁT
ALTER TABLE PROPERTY DROP CONSTRAINT CLIENT_FK;
-- TÖRLI A USER_DATA TÁBLA USER_ID ELSŐDLEGES KULCSÁT
ALTER TABLE USER_DATA DROP CONSTRAINT USER_ID_PK;
-- TÖRLI A PROPERTY TÁBLA PROPERTY_ID ELSŐDLEGES KULCSÁT
ALTER TABLE PROPERTY DROP CONSTRAINT PROPERTY_ID_PK;
-- TÖRLI A CLIENT TÁBLA CUSTOMER_ID ELSŐDLEGES KULCSÁT
ALTER TABLE CLIENT DROP CONSTRAINT CLIENT_ID_PK;
-- TÖRLI A TÁBLÁK TARTALMÁT
TRUNCATE TABLE USER_DATA;
TRUNCATE TABLE CLIENT;
TRUNCATE TABLE PROPERTY;
-- VISSZAÁLLÍTOM SORRENDBEN A TÁBLÁK MEGSZORÍTÁSAI
-- ELSŐDLEGES KULCSOK
ALTER TABLE USER_DATA ADD CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID);
ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_ID_PK PRIMARY KEY (CLIENT_ID);
ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_ID_PK PRIMARY KEY (PROPERTY_ID);
-- IDEGEN KULCSOK
ALTER TABLE PROPERTY ADD CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USER_DATA(USER_ID);
ALTER TABLE PROPERTY ADD CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID);