
DROP SEQUENCE PROPERTY_SEQ;
ALTER TABLE PROPERTY DROP CONSTRAINT PROPERTY_ID_PK;
ALTER TABLE PROPERTY DROP CONSTRAINT USER_FK;
ALTER TABLE PROPERTY DROP CONSTRAINT CLIENT_FK;

DROP TABLE PROPERTY;
  
  CREATE TABLE "ADMIN"."PROPERTY" 
   (	"PROPERTY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PROPERTY_TYPE" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"PROPERTY_SIZE" NUMBER(*,0) NOT NULL ENABLE, 
	"GROUND_SIZE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"NUMBER_OF_ROOM" NUMBER NOT NULL ENABLE, 
	"NUMBER_OF_HALF_ROOM" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER NOT NULL ENABLE, 
	"STREET_AND_NUMBER" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"CITY" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"MATERIAL" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TOILET" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ENERGETIC_LEVEL" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PROPERTY_CONDITION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"ADVERTISING_STATUS" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"VIEW_COUNTER" NUMBER(*,0), 
	 CONSTRAINT "PROPERTY_ID_PK" PRIMARY KEY ("PROPERTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."USER_DATA" ("USER_ID") ENABLE, 
	 CONSTRAINT "CLIENT_FK" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "ADMIN"."CLIENT" ("CLIENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_ID" IS 'Ingatlan egyedi azonosító';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."CLIENT_ID" IS 'Ügyfél azonosító';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."USER_ID" IS 'Felhasználó azonosító';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_TYPE" IS 'Cím típusa (Lakás, ház, telek, stb)';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_SIZE" IS 'Az ingatlan mérete(négyzetméterben)';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."GROUND_SIZE" IS 'Telek méret(négyzetméter), Háznél és irodánál!';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."NUMBER_OF_ROOM" IS 'Szobák száma';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."NUMBER_OF_HALF_ROOM" IS 'Félszobák száma';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."PRICE" IS 'Ár';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."STREET_AND_NUMBER" IS 'Cím';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."CITY" IS 'Város';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."MATERIAL" IS 'Ingatlan anyaga';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."TOILET" IS 'WC';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."ENERGETIC_LEVEL" IS 'Energetikai besorolás';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_CONDITION" IS 'Ingatlan állapota (Új építés, felújított, felújítandó, stb)';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."DESCRIPTION" IS 'Ingatlan leírás';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."ADVERTISING_STATUS" IS 'Hirdetés státusza';
   COMMENT ON COLUMN "ADMIN"."PROPERTY"."VIEW_COUNTER" IS 'Nézettség';

CREATE SEQUENCE PROPERTY_SEQ START WITH 1 INCREMENT BY 1;